### ISSUE TITLE
Unclosed angle brackets causing issue

### ISSUE THREAD

**Issue by thethreeonee** [pouyakary/ProColors#1]
When using with react, if there's unclosed angle brackets, the charactors behind is invisible.

![image](https://cloud.githubusercontent.com/assets/4125903/18084977/d0b0c66c-6edb-11e6-9e6a-b4fb90554c00.png)

![image](https://cloud.githubusercontent.com/assets/4125903/18084986/d62732c0-6edb-11e6-9c30-eddb4e0836aa.png)

**Comment by pouyakary** [comment]
can you give me an example code?

**Comment by thethreeonee** [comment]
``` javascript
import React, {Component, PropTypes} from 'react'

class Sample extends Component {
  render () {
    return (
      <div>

      </div>
    )
  }
}

Sample.propTypes = {

}

export default Sample
```

when enter `<asd` in `div`, it looks like this:

![image](https://cloud.githubusercontent.com/assets/4125903/18087819/aa4be99e-6ee9-11e6-9a6c-9e4678acebe6.png)

![image](https://cloud.githubusercontent.com/assets/4125903/18087825/aef44e6e-6ee9-11e6-8053-fc7d2e08a9ef.png)

**Comment by pouyakary** [comment]
## Fixed

@Murriouz: The bug is fixed. It was because of a problem within Visual Studio Code. The invalid code had to be rendered with a red background and white text. But Visual Studio Code has no support for background rendering. So I changed the invalid code to foreground color (vscode will automatically render an underline so you'll find if it's invalid)

## Commits:

![06cbf19af4203614cdaf8acf0be8e4f62043f64a](https://github.com/karyfoundation/karyfoundation.themeX/commit/06cbf19af4203614cdaf8acf0be8e4f62043f64a)
