### ISSUE TITLE
Php highlighting "broken" in 12.0.0?

### ISSUE THREAD

**Issue by m-thorsen** [pouyakary/ProColors#11]
Methods, statics, strings, arrays, even the brackets are all green (to me at least).

Before (11.1.0):
![karytheme-old](https://cloud.githubusercontent.com/assets/14907694/26091933/7c3579bc-3a0e-11e7-9237-ebed665a132d.png)

After (12.0.0):
![karytheme-new](https://cloud.githubusercontent.com/assets/14907694/26091932/7c1040fc-3a0e-11e7-9c16-499d97c187ed.png)

**Comment by coastermcgee** [comment]
I believe this is caused by the recently added scope for `text.html.php` which was implemented to colorize text and strings for php.  Since most php scopes are missing from the theme, everything is falling back to using this newly added scope and that's causing the vast amount of green you're seeing.

**Comment by pouyakary** [comment]
@m-thorsen thanks for reporting
@coastermcgee thanks for your comment, it was really helpful

Problem with PHP is we have no PHP users in KF and as I mentioned in #8 I don't know PHP so what I did was using a sample code containing most of the features from [Learn X in Y minutes](https://learnxinyminutes.com/docs/php/) and it actually worked great with that sample I'll be making a go back to v11 to fix this and try to make it better. Sorry for this problem
