### ISSUE TITLE
keep the activebar black in kary-light

### ISSUE THREAD

**Issue by transtone** [pouyakary/ProColors#16]
like the dark bar on top of `github.com`, leave a dark bar in the left is a design principles of contrast.
when the left activebar is dark, it can't bother me when coding.

as robin williams says in [Non-Designers-Design-Book](https://www.amazon.com/Non-Designers-Design-Book-4th/dp/0133966151): 

`Contrast on a page draws our eyes to it; our eyes like contrast. If you are putting two elements on the page that are not the same (such as two typefaces or two line widths), they cannot be similar—for contrast to be effective, the two elements must be very different.`

**Comment by pouyakary** [comment]
Hi @transtone. Thanks for using Kary Themes. We love ideas on the theme but this one has been one of our main design principles _not to have an active bar with dark background_.

Contrast is good however that much contrast is bad. Contrast must be of some level not opposite of a color. If you look at the light theme there's a contrast on colors between the editor and sidebar / active bar. Also we have made several issues on the vscode's main repo and brought a better support of __contrast borders__ and all the parts that needs to be separated are now separated using contrast borders instead of contrast color. 

Still the only two distinct parts that are now in one level of color are the active bar and side bar. Our theme renders poor on vscode 12. if you get the vs 13 you'll see improvements by some order and hope the contrast borders get better in your editor so that you find the contrast comforting and not bothering.
