### ISSUE TITLE
Kary Light in high resolution tires the eye

### ISSUE THREAD

**Issue by mpourismaiel** [pouyakary/ProColors#18]
I don't know if this counts as an issue on the theme or my monitor or even my eye. I'm using a 4k display and VSCode maximised. As you can see in the screenshot below there is way too much whitespace and when I'm focused on the code it quickly tires my eye. I've changed the background color to `#eee` as you suggested but it doesn't help very much. Also doing this makes current line almost indistinguishable.

![image](https://user-images.githubusercontent.com/14017717/29996769-e2f825f8-9019-11e7-864b-fcf0a3e9c94b.png)

Without the color configuration, it looks like this:

![image](https://user-images.githubusercontent.com/14017717/29996776-10cca864-901a-11e7-9e98-21eb043f51e7.png)

**Comment by pouyakary** [comment]
I agree with you, The light theme is based on light apps so the ideal is to have a theme that is light enough that if you switch from github to your editor your eyes are not going to get hurt but also it's a bit gray (a very tiny tiny bit as the background is `#F7F7F7`).

You're problem is mostly with your font and the very wide screen. You use Fira regular/light which effectively effects the color of the tokens (when you use light/regular fonts in the light theme, shading pixels get more bright and because the stroke is tin their light &mdash; as they are brighter &mdash; makes main stroke colors less viewable) and therefore the overall brightness looks much more bright. Also because of the very wide screen you experience an awful lot of negative space.

Whatever happens to the theme, your widescreen will not be fixed. This is very common problem within white interfaces. If you remember back in the iOS 7/8 a massive amount of negative white spaces was added to the UI and that made many not comfortable. Also you look at the next versions such as 9-11 most of the UI changes was about reducing those whitespaces (some apps even fully changed to dark)

Now it's hard to find a great solution here. We ran to this months before as themes are too light and too dark. My solution was to have a middle theme (an evening one): [Woolen](https://marketplace.visualstudio.com/items?itemName=karyfoundation.theme-woolen). It wasn't that pretty and soon got deprecated.

Also there is a problem with harmony because changing the background effectively breaks the whole harmony. I can't introduce a completely new color into the theme that easily, for that sake using `#EEEEEE` was a very rational decision because its the darkest light gray in the light theme.

Main Light theme should look like this:

<img width="1030" alt="screen shot 2017-09-02 at 10 26 14 pm" src="https://user-images.githubusercontent.com/2157285/29997660-02e75122-902e-11e7-87ca-e17e9a47860f.png">

(BTW, do you see the difference between my theme and your theme? that's because I use a medium size typeface of weight 600 and I highly recommend you use darker typefaces too.)

My current proposition is to have a `#EEEEEE` as the background by that we should tweak some other colors such as line's background highlight and border as well as panel colors, etc. which results in this:

<img width="1033" alt="screen shot 2017-09-02 at 10 26 03 pm" src="https://user-images.githubusercontent.com/2157285/29997668-5f2794f6-902e-11e7-9004-212142c21849.png">

Now this is still light years behind acceptable so let me hang around and try more combinations and harmonize the mood. But as said I promise you'll get a new theme called `Eye Light` very soon.

**Comment by mpourismaiel** [comment]
In the meantime, I took your advice and changed the font weight to a bit bolder weight and the results are a bit better. I can't wait for the new theme. Thanks, mate ;)
