### ISSUE TITLE
Color contrast in references panel

### ISSUE THREAD

**Issue by jiayihu** [pouyakary/ProColors#19]
When showing the references, the list of filenames are barely readable if not selected.
![schermata 2017-09-24 alle 19 43 25](https://user-images.githubusercontent.com/10067273/30785222-5b92f74a-a163-11e7-985b-5f3e0ad1e420.png)

**Comment by pouyakary** [comment]
Thanks a lot for reporting, I'm on it...

**Comment by takato1314** [comment]
Hello.

First of all. Thanks for creating such a cool theme. I really love the design that you created.

As aforementioned, i also found the same issue for the dark theme. Please refer to the screenshot:
<img width="411" alt="2017-10-19_0-00-39" src="https://user-images.githubusercontent.com/10910968/31729318-4477dfec-b461-11e7-8456-697a218c38a1.png">

Also, i will very appreciate too if you can use a darker color for the mouseover color as shown in the screenshot. Currently, it uses greyish-blue but it doesnt seem to be very clear.

**Comment by pouyakary** [comment]
Hello @takato1314, thanks a lot for reporting.

First of all: Did you set the parenthesis and curly brace colors? why are they magenta and blue?

And also thanks a lot for the reporting. I'm very sorry to see this happening. I'll be surely fixing that.

**Comment by takato1314** [comment]
Hi @pmkary , thx for the prompt reply. FYI, the coloring of the brackets and curly braces are due to a plugin known as 'bracket-pair-colorizer' (https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer).

Below shows the effect after disabling that plugin and all colorizer plugins that i have:
<img width="729" alt="2017-10-19_13-42-14" src="https://user-images.githubusercontent.com/10910968/31756022-33fd4bd4-b4d4-11e7-8ba3-9681e92b4e5c.png">

As you can see, the words in the reference panel are also not clear during normal/ onmouseover.

**Comment by pouyakary** [comment]
@takato1314 ah good Buddha... We have a long history with braces being rendered in green and if you read release notes you'll notice how much of the bug fixes each time is in regards of brace colors. We don't have those colors in the theme and when I looked at your picture I was like "How this could have happened". Thanks a lot for clarifying this

**Comment by pouyakary** [comment]
@jiayihu @takato1314 @moskal91

Thanks a a lot for your collaboration on this issue. The peek view is a million miles to be perfect but I guess this issue is now resolved. I hope you never experience such problems again. 

<img width="971" alt="screen shot 2017-10-30 at 3 02 52 pm" src="https://user-images.githubusercontent.com/2157285/32168877-6f3ced5a-bd83-11e7-8248-fad53c1adda8.png">
