### ISSUE TITLE
Yellow color contrasts in Eye Light theme

### ISSUE THREAD

**Issue by oyeanuj** [pouyakary/ProColors#23]
Hi @pmkary, firstly, thank you for the excellent work in developing these themes. It is the first light theme that I've gotten to and is actually pleasant to the eye!

The only thing that I see myself squinting at always is the yellow color, like you'd see in the screenshot here: https://cl.ly/0L1C231o1K31

<img width="604" alt="screen shot 2018-02-17 at 11 58 06 am" src="https://user-images.githubusercontent.com/9633371/36345103-dcb175d4-13d9-11e8-8f18-65bdcbb7a96d.png">

Notice the yellow paranthesis in the screenshot above. I appreciate the intention there of driving the focus to the actual code that matters but if you have some nested code like that, it becomes hard to see if that is a ')' or '}' and feels a little too close to the off-white background.

I wonder if you agree that the contrast there could be experimented with?

**Comment by pouyakary** [comment]
Hi Anuj! Thanks a lot for that kind comment :D I really am happy that it's pleasant to you!

The colors are not defined within the themes. They are based on a plugin. I don't remember the name but I have seen it previously. One of the other users once showed me an screenshot with that color. I first though it's a bug but turned out that it's by an independent plugin. So nothing I can do for you about it. You should probable change the settings of your plugin.

All the punctuations in the light themes must be the black (which in light theme's world is `#1A1A1A`. The themes are made with a custom built generator and I use variables to store the color values so if the I change the color of a yellow every single yellow (editor-wide) will change and therefore seeing one thing not being the same color as others defiantly is not by the themes

Please check your plugins and keep me in touch, I hope the problem be solved. till more info I will label this issue as non-related and close it. Please if you found more info reopen the comment and let me know

thanks a lot for your contribution

**Comment by oyeanuj** [comment]
@pmkary So, you were right about this. It turns out that this is VSCode adding that color by default via is Monaco Editor engine. Not sure if there is anything that can be done about it. This is their list but not sure which of those matches the paranthesis - https://code.visualstudio.com/docs/getstarted/theme-color-reference

Oh, well. Thanks for your help though!

**Comment by pouyakary** [comment]
Can you do something? In vscode go to he command palate and run this:

<img width="735" alt="screen shot 1397-01-07 at 4 47 32 pm" src="https://user-images.githubusercontent.com/2157285/37966751-a20b06c0-31de-11e8-8b28-70dc39517ae0.png">

When you run this tool you can navigate on the editor and find out what token it found for each colored element on the screen:

<img width="896" alt="screen shot 1397-01-07 at 4 47 45 pm" src="https://user-images.githubusercontent.com/2157285/37966930-1a131b76-31df-11e8-8901-8f288ef529a2.png">

Then you can find out what is exactly causing that color. When you found it you can go to your settings and use this technique: 

<img width="368" alt="screen shot 1397-01-07 at 4 54 19 pm" src="https://user-images.githubusercontent.com/2157285/37967078-870665bc-31df-11e8-99d7-771bbaa85488.png">

This will hopefully resolve your problem. I hope it works.

**Comment by oyeanuj** [comment]
@pmkary thank you for those tips! I got stuck at the last step. Here is what the popup looks like for me: 
![image](https://user-images.githubusercontent.com/9633371/38002244-ed7b1d64-31e5-11e8-9d39-89f5222430c9.png)


Interestingly, it seems the color is not event showing up, and neither can I figure out the token id from that popup. Any ideas?

**Comment by pouyakary** [comment]
It's really strange. Tokenizer has found `meta.brace` and `meta.brace.round.js` and for both of them it has successfully set `#1A1A1A` as the color. So it's defiantly because of a TypeScript API.  Try disabling extensions one by one, you might find the root of the problem.
