### ISSUE TITLE
Themes for Prism?

### ISSUE THREAD

**Issue by oyeanuj** [pouyakary/ProColors#24]
Hi @pmkary, back again with a hopeful question - have you made or considered making the Kary themes for PrismJS library?  Apart from my self-interest in being able to use it, it will also help promote the themes more given the popularity of PrismJS - https://github.com/PrismJS/prism-themes

**Comment by pouyakary** [comment]
Hi @oyeanuj, good to see you again.

To be honest I've thought of having ports for other editors. Yet what happens is a rather philosophical problem: "how do you define a theme?". When it comes to one app, it's just easy to define a theme: it's the sum of all of it's changeable settings. But when it comes to porting themes it becomes rather difficult to define a theme, If you take two apps and try to define a theme that exists on both of theme you have two sets of settings each of which has their own things. So now you have to define a theme by one of these definitions:

- A theme is the union of all the settings
- A theme is the intersection of all the settings

Now what makes it really hard is that if you go with the first definition you'll loose because of the editors can only support a part of the theme and it wouldn't work. That's why you always have to go with the second definition. 

And to go with the second definition you have to reduce the theme to a point where it works on every editor. Problem is, each editor has their own tokenizer and therefore language grammars are really different across all editors. 

At first I defined the theme as only a set of colors with known comment color, keyword color, background color, etc. So it was easy to port it to everywhere because it was too basic. Yet it looked like this:

<img width="515" alt="screen shot 2016-07-23 at 1 04 23 pm" src="https://user-images.githubusercontent.com/2157285/39195097-546bbe10-47f4-11e8-8520-87cfa049d2e9.png">

Which wasn't that bad but what made the theme good was the point where I changed my policy. And my new policy was (and still is) to define a color scheme, such that any combination of tokens look harmonious and in a way that colors be used based on the frequency of the appearance of a token. This policy needed a much deeper control over the tokens to a point in which I could style every single token. 

This policy needs really well defined grammars. For now only TypeScript, JavaScript, C++, PEG.js, Go and the grammars that I developed are defined this good and the problem with these grammars is that they need such high end tokenizers that you can only find them on VSCode, Atom, TextMate and Sublime.

Take this for example:

<img width="563" alt="screen shot 1397-02-04 at 7 32 33 pm" src="https://user-images.githubusercontent.com/2157285/39195999-4ce897e2-47f6-11e8-8492-677d4490f3fd.png">

This is a PEG.js grammar with inline JavaScript and I could style every single token in PEG.js to look good and natural with JavaScript. But each time I try to port this theme to other editors. It ends up like this:

<img src="https://user-images.githubusercontent.com/2157285/39196077-818d49f2-47f6-11e8-8925-52668ef27188.jpg" width="300">

Most of the things share a common token definition (for example `def` must be orange to match with the red name of the function but it counts as a keyword and therefore it you can't change it) also must of the text is black and you can't do anything about it.

Because of this I got stuck on only supporting VSCode. So I have no idea, if Prism can support tmLanguage definitions then it would be possible to write a themeX definition for it and support it but for what I've seen from the examples it's tokenizer looks limited too.

**Comment by pouyakary** [comment]
Feel free to continue the discussion. I only closed the issue to not count as an unsolved problem.

**Comment by oyeanuj** [comment]
@pmkary Thanks as always for the detailed thoughtful response. I definitely see your dilemma.

> At first I defined the theme as only a set of colors with known comment color, keyword color, background color, etc. 

I feel like this is one of those cases that something feels better than nothing, and feels a step-up from the current themes. I don't think that prismJS tokenizer is gonna be that satisfactory but even starting with a basic version, and making it a feature request with Prism to have a more advanced tokenizer would be super helpful. That way, people can use the basic harmonious themes and then as more support gets added in Prism, then it can get fancier.

If you do opt for that approach, you could even append the word 'basic' to  the theme names, so that folks who are familiar with your themes don't have unrealistic expectations.

**Comment by pouyakary** [comment]
@oyeanuj Your idea is actually pretty good. I will definitely consider that. Can't grantee any deadline but maybe even sometime soon.

**Comment by oyeanuj** [comment]
Sounds great, looking forward to it :)
