### ISSUE TITLE
Looks different 

### ISSUE THREAD

**Issue by idoo** [pouyakary/ProColors#27]
For some reasons them in my VSC looks completely different than on an example ( I guess something wrong with contrast)

<img width="1743" alt="39585670-942a19bc-4f0a-11e8-9bba-f1ae1471ef5c png 2560x1556 2018-11-22 10-10-12" src="https://user-images.githubusercontent.com/738921/48887021-ef998980-ee3e-11e8-8daa-fec4476a42c9.png">

any ideas how to fix it?

**Comment by pouyakary** [comment]
Hello @idoo and yes. That is due to the VS Code settings of yours. Mine has some important difference. First I use the main "Light" while you have chosen the "Eye Light" that is the big background difference.

Also to get the colors right you need to have bold fonts. (the white color of the surrounding pixels makes the colors look bad). I use the beautiful medium weight of [Hasklig](https://github.com/i-tu/Hasklig) typeface.

There are also other factors, you have such small indentation and spacing that makes the screen to be left half empty, I use 4 space indentations, a large font size (13) and large line height (27) which makes my screen to be almost full of text always and therefore the background color has less effect.

More than that I avoid the indentation lines and thus the screen looks much cleaner.
