### ISSUE TITLE
Ask for the theme on Mac iterm2 :)

### ISSUE THREAD

**Issue by WindSoilder** [pouyakary/ProColors#28]
Hi, Vary appreciate for your theme, I love it very much.
But sadly I can't use it on Mac iterm2.  May you please add this theme for item2 ?

**Comment by pouyakary** [comment]
@WindSoilder hi! thanks for using Pro Colors :D 

A big problem with the terminals is they need two tones for each color (a dark and a bright one). Currently I don't have that for terminals. But I'm thinking about it because I want to have Pro Colors on the Terminal too. Once I figured out a good color match I will definitely release a Terminal version for a few of the famous ones including iTerm 2.

**Comment by gpaulsen** [comment]
@pouyakary Did someone eventually post an iTerm2 color preset?  link?  Thanks!

**Comment by pouyakary** [comment]
@gpaulsen what link?
