### ISSUE TITLE
Poor Contrast Entering Text via User Snippet

### ISSUE THREAD

**Issue by jasonjohnson47** [pouyakary/ProColors#29]
First, compliments on the theme. It's by far my favorite. Thank you for creating it and all your effort!

In the light theme, when inserting HTML (or CSS) via a user snippet and then typing into the tabstop via the $1 in the html.json or css.json file, the contrast between the highlight background color and foreground text color is poor, especially for comments. See attached screenshot.

![editor-comment-example](https://user-images.githubusercontent.com/20387358/50181182-a885a380-02d9-11e9-8f22-64d27f103591.png)

**Comment by pouyakary** [comment]
Hi! thank for using Pro Colors and your kind words! I didn’t know this thing existed and honestly have no I idea where does that highlight color comes form. I will try to recreate the incident, but since the definition of Pro Colors does not have any color that even looks like that background, I believe that is due to colorization of an extension. So while I try to see if that happens in my machine as well, please test this in an environment with your extentions disabled to trace the origin

**Comment by jasonjohnson47** [comment]
Thank you for looking into it! I believe that is all built-in features and functionality of VS Code. See the documentation here:
[https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets](url) 
and
[https://code.visualstudio.com/docs/editor/userdefinedsnippets#_tabstops](url)

**Comment by pouyakary** [comment]
@jasonjohnson47 so I checked it out and yeah you're right it seems that my definitions for snippets were damaged, so I added some new ones. In the next release this is fixed.
