### ISSUE TITLE
Differentiate const and let

### ISSUE THREAD

**Issue by nonameolsson** [pouyakary/ProColors#38]
Thanks for a great theme!

Would it be possible to adjust the colors for `const` and `let` variables in JavaScript/TypeScript? They use the same color right now.

## Kary Pro Theme

**Kary Pro Dark**
![image](https://user-images.githubusercontent.com/1493018/214505742-000550c9-258d-47f3-9dae-c8ab4d609993.png)

**Kary Pro Light**
![image](https://user-images.githubusercontent.com/1493018/214505785-bb647ebc-5f09-403a-9386-f44f86098887.png)

## Other themes

**Dark+**
![image](https://user-images.githubusercontent.com/1493018/214505853-fe1f478c-c83e-43c7-ab76-7605a78b8926.png)

**Dark+ V2 (Experimental)**
![image](https://user-images.githubusercontent.com/1493018/214505927-d3fe5fe5-6d38-4b97-b3f4-57a3230ca971.png)

**GitHub Dark Default**
![image](https://user-images.githubusercontent.com/1493018/214505889-cb713f04-d273-4a87-88b2-836bdd0c6de2.png)

**Light+**
![image](https://user-images.githubusercontent.com/1493018/214506272-c6736fad-5d13-44fb-a4fd-111b5046389f.png)

**Light+ V2 (Experimental)**
![image](https://user-images.githubusercontent.com/1493018/214506297-9682da44-ea0d-4e89-8919-a8424833ee18.png)

**GitHub Light Default**
![image](https://user-images.githubusercontent.com/1493018/214506341-19bc0598-212c-43b5-ac70-cca51372440d.png)

**Comment by pouyakary** [comment]
@nonameolsson this is interesting, let me try some variations on it and see if I'll add it to the theme. However I'm only adding it if the colors are consistent everywhere.

**Comment by nonameolsson** [comment]
Hey @pouyakary ! 
Have you had the opportunity to look into this? Is it something that you are willing to add?

**Comment by pouyakary** [comment]
Hey @nonameolsson, I have applied green to constants in JS/TS in ProColors, but I'm not sure if it works on all languages. So in the version 34.2 you'll get the update!

**Comment by nonameolsson** [comment]
This looks really good, just tested it!
I'm just wondering about light theme. Is that version also including a different color for cont/let?

**Comment by pouyakary** [comment]
@nonameolsson Thanks a lot! I'm happy that you had fun! 

Yes it does, Pro Colors is built with a tool called [themeX](http://github.com/pouyakary/themex) which supports the idea of different palates implementing the same scope set. So the rules behind the Light and Dark themes are shared and then they only get the different colors based on the palates. And since the dark version has only a different shade of the light colors (blue, green, red, orange, purple, comment and gray) the two are exactly the same.

**Comment by nonameolsson** [comment]
> 

That sounds interesting! 👍🏻 

The reason I asked is that I can't see a difference in the light theme 😸  This is how I see it: 
<img width="211" alt="image" src="https://github.com/pouyakary/ProColors/assets/1493018/083fe06f-549d-4e7f-86cf-1c6f130dc2d2">
<img width="243" alt="image" src="https://github.com/pouyakary/ProColors/assets/1493018/aa5fa7cd-f9d6-4403-be52-807217cfcf1c">

Is this expected?

**Comment by pouyakary** [comment]
Oh good thing you asked it then. I must have messed up the build pipeline and it must have not updated the light version. Thanks for bringing it out. I'll fix it soon.

**Comment by nonameolsson** [comment]
> Oh good thing you asked it then. I must have messed up the build pipeline and it must have not updated the light version. Thanks for bringing it out. I'll fix it soon.

Thanks for all the work on this! Did you manage to find a solution for the light theme?

**Comment by pouyakary** [comment]
@nonameolsson I'm afraid I'm going to have to revert this change. It has caused problems with my friends and now there is even an issue around it. So probably in the future versions, the colors will be turned back to blue. What you can do however is to define specifically in your vscode theme settings a different color for the constants and feel no change. Once I'll go to change the code I provide you with the settings that you can copy and paste in your editor.

**Comment by jiayihu** [comment]
I can see the original rational for the request to differentiate between `const` and `let`. My complaint is instead about the fact that now `const` has the same color as `types`, which is very confusing in TypeScript. Notably with renaming destructured variables, it's very easy to misread it as type:

<img width="401" alt="Screenshot 2024-05-13 at 23 37 05" src="https://github.com/pouyakary/ProColors/assets/10067273/44897b82-54c1-4a6e-9f95-92f625795a48">

But I don't believe my view trumps over @nonameolsson 's request, especially since I'm the first to report it. If you can point me the setting @pouyakary I can just use that. 


EDIT: With a bit of reverse engineering I found the setting:

```json
"editor.tokenColorCustomizations": {
  "[Kary Pro Colors － Light]": {
    "textMateRules": [
      {
        "scope": "variable.other.constant",
        "settings": {
          "foreground": "#3778B7"
        }
      }
    ]
  },
  "[Kary Pro Colors － Dark]": {
    "textMateRules": [
      {
        "scope": "variable.other.constant",
        "settings": {
          "foreground": "#819DC2"
        }
      }
    ]
  }
},
```
