### ISSUE TITLE
Differentiate focused file from other

### ISSUE THREAD

**Issue by FEsteven** [pouyakary/ProColors#39]
Hi,
First thanks to this great theme.
One thing that's bothering me: it's hard to differentiate the focused and unfocused tabs (in the tab bar).

Pro colors Dark theme (v32.3.0 latest in visual studio marketplace):
![Capture d’écran du 2023-03-17 11-46-15](https://user-images.githubusercontent.com/537877/225885276-72790c2b-faca-4514-868a-3622dcfd8636.png)

Default dark+ theme :
![Capture d’écran du 2023-03-17 11-47-28](https://user-images.githubusercontent.com/537877/225885367-62528f3b-e9ad-4310-913e-167310a07394.png)

Thanks
Fabien

**Comment by pouyakary** [comment]
Hey @Fafou! I'm glad that you like the theme :)

Pro Colors uses borders to show the active tab (which seems to be disabled for you)

<img width="589" alt="Screenshot 1401-12-27 at 10 36 21 PM" src="https://user-images.githubusercontent.com/2157285/226131082-b2150ba4-d74a-4796-8173-71522df0b20a.png">

The thing is that I cannot change the theme because of your specific preference over disabling the bars. But the good news is VS Code is incredibly flexible when it comes to customizations. And you can actually change Pro Colors to your likings. If you don't want bars that's okay, you can personalize it by adding this to your settings.json:

```
{
    "workbench.colorCustomizations": {
        "[Kary Pro Colors － Dark]": {
            "tab.activeBackground": "#000000",
        }
    }
}
```

I'm not sure what would be a good color for you, because I already have put the color I like in the theme. But I think `#000000` or `#1A1A1A` are good starting points.

Have fun!

**Comment by FEsteven** [comment]
Hi @pouyakary thanks for your answer.
I found why the active tab don't have a border.
I think it's a bug in vscode, I use zoom -2.
With 0 or -1 i have a border, with -2 I don't have this border, I think this border don't have a minimal width.
Thanks for the trick with color customizations it work very well.

Fabien

**Comment by pouyakary** [comment]
You're very welcome! Hope you have fun!
