### ISSUE TITLE
JSON is not correctly colored when an Array

### ISSUE THREAD

**Issue by smlombardi** [pouyakary/ProColors#4]
I like the sample screenshot of JSON with the green key names and blue key value strings.  However, my JSON files do not look like that:

![screen shot 2016-11-01 at 4 54 53 pm](https://cloud.githubusercontent.com/assets/835148/19907186/25eb91b2-a054-11e6-8bd6-d14087b95a23.jpg)

**Comment by pouyakary** [comment]
@smlombardi thank you so much for pointing that out and for using our theme! I have to ask what version of vscode are you using? and what version of kf theme?

The truth is that vscode is changing the javascript/typescripts and due to that I'm redefining the whole thing to keep compatibility and the new definitions are really really bad and not complete. So some stuff are going to get changed or look strange. I'm going to make some pull requests to the def files with improvements and make some issues in the repo to see what happens. In the side I will try to investigate this as much as I can.

**Comment by smlombardi** [comment]
KF 7.4.0
Version 1.7.0-insider (1.7.0-insider)

**Comment by pouyakary** [comment]
thanks a lot 👍  I'll be checking that out very soon

**Comment by pouyakary** [comment]
@smlombardi sorry for the very late updates on this issue:

<img width="386" alt="screen shot 2016-11-18 at 2 04 30 am" src="https://cloud.githubusercontent.com/assets/2157285/20410664/6df14da8-ad33-11e6-91fe-c0b1e411a10d.png">

I've added a custom definition for the JSON and now I'm working on the YAML definitions. Very soom you'll be provided with a great new theme.

Thanks a lot for your patience
