### ISSUE TITLE
Improve syntax highlighting for PHP

### ISSUE THREAD

**Issue by coastermcgee** [pouyakary/ProColors#8]
I've been working with the light theme in VS Code and am loving it so far!  

I'm just wondering if there's any chance for improved PHP support?  It doesn't look like much tweaking is needed but I'm coding in Laravel at the moment and have noticed some things aren't being colorized (classes in use statement, classes/methods called statically, etc):

<img width="455" alt="example" src="https://cloud.githubusercontent.com/assets/24684963/23320066/3e8405c6-faa7-11e6-90fa-61cb9ac0e521.png">

Thanks!

**Comment by pouyakary** [comment]
@coastermcgee thanks a lot for using this theme. There are no PHP devs in our team so this things happens. I can use this code as an example to include all the stuff that is in the lang:

https://learnxinyminutes.com/docs/php/

Is this enough or you want an specific thing? And also this will take time because we are a bit busy right now. Hope that's no problem to you :D

**Comment by coastermcgee** [comment]
Yep no problem, that sounds great!  Thanks again!
